[package]
name = "inky-gotchi"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2.6"
linux-embedded-hal = "0.3.2"
profont = "0.5.0"
embedded-graphics = "0.7.1"
embedded-graphics-simulator = "0.3.0"
ssd1675 = { path = "./ssd1675" }
